routes/web.php
<?php

use App\Http\Controllers\Client\HomeController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index']);

Route::get('/dashboard', function () {
    return view('admin.dashboard.index');
})->name('dashboard');

Route::get('/home', function () {
    return view('client.layouts.app');
});

Auth::routes();

Route::resource('roles', \App\Http\Controllers\Admin\RoleController::class);
Route::resource('users', \App\Http\Controllers\Admin\UserController::class);
Route::resource('categories', \App\Http\Controllers\Admin\CategoryController::class);
Route::resource('products', \App\Http\Controllers\Admin\ProductController::class);

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\Permission\Models\Role as ModelsRole;

class Role extends ModelsRole
{
    use HasFactory;

    protected $guarded = [];

}

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Roles\CreateRoleRequest;
use App\Http\Requests\Roles\UpdateRoleRequest;
use App\Models\Permission;
use App\Models\Role;
use Illuminate\Http\Request;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $roles = Role::latest('id')->paginate(5);
        return view('admin.roles.index', compact('roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $permissions = Permission::all()->groupBy('group');
        return view('admin.roles.create', compact('permissions'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateRoleRequest $request)
    {
        $dataCreate = $request->all();
        $dataCreate['guard_name'] = 'web';
        $role = Role::create($dataCreate);
        $role->permissions()->attach($dataCreate['permission_ids']);
        return to_route('roles.index')->with(['message' => 'Tạo Thành Công!']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $role = Role::with('permissions')->findOrFail($id);
        $permissions = Permission::all()->groupBy('group');
        return view('admin.roles.edit', compact('role', 'permissions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRoleRequest $request, $id)
    {
        $role = Role::findOrFail($id);
        $dataUpdate = $request->all();
        $role->update($dataUpdate);
        $role->permissions()->sync($dataUpdate['permission_ids']);
        return to_route('roles.index')->with(['message' => 'Sửa Thành Công!']);

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Role::destroy($id);
        return to_route('roles.index')->with(['message' => 'Xóa Thành Công!']);
    }
}

resources/views/admin/roles/create.blade.php
@extends('admin.layouts.app')

@section('title', 'Tạo Roles')

@section('content')
    <div class="col-12">
        <div class="card my-4">
            <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
                    <h6 class="text-white text-capitalize ps-3">Tạo Role</h6>
                </div>
            </div>
            <div class="card-body">
                <form action="{{ route('roles.store') }}" method="post">
                    @csrf
                    <div class="input-group input-group-static mb-4">
                        <label>Tên</label>
                        <input type="text" value="{{ old('name') }}" name="name" class="form-control" placeholder="Nhập tên Role">

                        @error('name')
                        <span class="text-danger"> {{ $message }}</span>
                        @enderror
                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label>Tên Hiển Thị</label>
                        <input type="text" value="{{ old('display_name') }}" name="display_name" class="form-control" placeholder="Nhập tên hiển thị Role">
                        @error('display_name')
                        <span class="text-danger"> {{ $message }}</span>
                        @enderror
                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label name="group" class="ms-0">Nhóm</label>
                        <select name="group" class="form-control">
                            <option value="system">System</option>
                            <option value="user">User</option>
                        </select>

                        @error('group')
                        <span class="text-danger"> {{ $message }}</span>
                        @enderror
                    </div>


                    <div class="form-group">
                        <label for="">Permission</label>
                        <div class="row">
                            @foreach ($permissions as $groupName => $permission)
                                <div class="col-5">
                                    <h4>{{ $groupName }}</h4>
                                    <div>
                                        @foreach ($permission as $item)
                                            <div class="form-check">
                                                <input class="form-check-input" name="permission_ids[]" type="checkbox"
                                                       value="{{ $item->id }}">
                                                <label class="custom-control-label"
                                                       for="customCheck1">{{ $item->display_name }}</label>
                                            </div>
                                        @endforeach
                                    </div>
                                </div>
                            @endforeach
                        </div>
                    </div>
                    <button type="submit" class="btn btn-submit btn-primary">Tạo</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/roles/edit.blade.php
@extends('admin.layouts.app')

@section('title', 'Sửa Roles' . $role->name)

@section('content')
    <div class="col-12">
        <div class="card my-4">
            <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
                    <h6 class="text-white text-capitalize ps-3">Sửa Role</h6>
                </div>
            </div>
            <div class="card-body">
                <form action="{{ route('roles.update', $role->id) }}" method="post">
                    @csrf
                    @method('PUT')
                    <div class="input-group input-group-static mb-4">
                        <label>Tên</label>
                        <input type="text" value="{{ old('name') ?? $role->name }}" name="name" class="form-control" placeholder="Nhập tên Role">

                        @error('name')
                        <span class="text-danger"> {{ $message }}</span>
                        @enderror
                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label>Tên Hiển Thị</label>
                        <input type="text" value="{{ old('display_name') ?? $role->display_name }}" name="display_name" class="form-control" placeholder="Nhập tên hiển thị Role">
                        @error('display_name')
                        <span class="text-danger"> {{ $message }}</span>
                        @enderror
                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label name="group" class="ms-0">Nhóm</label>
                        <select name="group" class="form-control" value="{{$role->group}}">
                            <option value="system" >System</option>
                            <option value="user">User</option>
                        </select>
                        @error('group')
                        <span class="text-danger"> {{ $message }}</span>
                        @enderror
                    </div>


                    <div class="form-group">
                        <label for="">Permission</label>
                        <div class="row">
                            @foreach ($permissions as $groupName => $permission)
                                <div class="col-5">
                                    <h4>{{ $groupName }}</h4>
                                    <div>
                                        @foreach ($permission as $item)
                                            <div class="form-check">
                                                <input class="form-check-input" name="permission_ids[]" type="checkbox"
                                                       {{$role->permissions->contains('name', $item->name) ? 'checked' : ''}}
                                                       value="{{ $item->id }}">
                                                <label class="custom-control-label"
                                                       for="customCheck1">{{ $item->display_name }}</label>
                                            </div>
                                        @endforeach
                                    </div>
                                </div>
                            @endforeach
                        </div>
                    </div>
                    <button type="submit" class="btn btn-submit btn-primary">Sửa</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/roles/index.blade.php
@extends('admin.layouts.app')

@section('title', 'Roles')

@section('content')
    <div class="col-12">
        <div class="card my-4">
            <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
                    <h6 class="text-white text-capitalize ps-3">Danh Sách Role</h6>
                </div>
            </div>
            <div class="card-body">
                @if(session('message'))
                    <div class="text-success text-4xl">{{session('message')}}</div>
                @endif
                    <a href="{{ route('roles.create') }}" class="btn btn-primary">Tạo</a>
                <div class="table-responsive p-0">
                    <table class="table table-hover align-items-center mb-0">
                        <thead>
                        <tr>
                            <th class="text-uppercase text-secondary text-md font-weight-bolder opacity-7">ID</th>
                            <th class="text-uppercase text-secondary text-md font-weight-bolder opacity-7 ps-2">Tên
                            </th>
                            <th class="text-uppercase text-secondary text-md font-weight-bolder opacity-7 ps-2">
                                Tên Hiển Thị
                            </th>
                            <th class="text-secondary opacity-7 ps-2"></th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach ($roles as $role)
                        <tr>
                            <td>
                                <div class="d-flex px-2 py-1">
                                    <div class="d-flex flex-column justify-content-center">
                                        <h6 class="mb-0 text-md align-middle" style="padding-left: 0.6rem">{{$role->id}}</h6>
                                    </div>
                                </div>
                            </td>
                            <td>
                                <p class="text-md font-weight-bold mb-0">{{$role->name}}</p>
                            </td>
                            <td>
                                <p class="text-md font-weight-bold mb-0">{{$role->display_name}}</p>
                            </td>
                            <td class="align-middle">
                                <a href="{{route('roles.edit', $role->id)}}" class="btn btn-outline-success font-weight-bold text-xs">
                                    Sửa
                                </a>
                                <form action="{{ route('roles.destroy', $role->id) }}"
                                    id="form-delete{{ $role->id }}" method="post">
                                    @csrf
                                    @method('delete')                                </form>
                                <button class="btn btn-delete btn-danger" data-id={{ $role->id }}>Delete</button>
                            </td>
                        </tr>
                        @endforeach
                        </tbody>
                    </table>
                    {{$roles->links()}}
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
<script></script>
@endsection