routes/web.php
<?php

use App\Http\Controllers\Client\HomeController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index']);

Route::get('/dashboard', function () {
    return view('admin.dashboard.index');
})->name('dashboard');

Route::get('/home', function () {
    return view('client.layouts.app');
});

Auth::routes();

Route::resource('roles', \App\Http\Controllers\Admin\RoleController::class);
Route::resource('users', \App\Http\Controllers\Admin\UserController::class);
Route::resource('categories', \App\Http\Controllers\Admin\CategoryController::class);
Route::resource('products', \App\Http\Controllers\Admin\ProductController::class);

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;
    protected $guarded = [];

    public function parent() {
        return $this->belongsTo(Category::class, 'parent_id');
    }

    public function childrens() {
        return $this->hasMany(Category::class, 'parent_id');
    }

    public function getParentNameAttribute() {
        return optional($this->parent)->name;
    }

    public function getParents() {
        return Category::whereNull('parent_id')->get(['id', 'name']);
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Categories\CreateCategoryRequest;
use App\Models\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    protected $category;

    public function __construct(Category $category)
    {
        $this->category = $category;
    }

    public function index()
    {
        $categories = $this->category->latest()->paginate(5);
        return view('admin.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $parentCategories = $this->category->getParents();
        return view('admin.categories.create', compact('parentCategories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateCategoryRequest $request)
    {
        $dataCreate = $request->all();
        $category = $this->category->create($dataCreate);
        return redirect()->route('categories.index')->with(['message' => 'Tạo danh mục mới thành công!']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = $this->category->with('childrens')->findOrFail($id);
        $parentCategories = $this->category->getParents();
        return view('admin.categories.edit', compact('category', 'parentCategories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $dataUpdate = $request->all();
        $category = $this->category->findOrFail($id);
        $category->update($dataUpdate);
        return redirect()->route('categories.index')->with(['message' => 'Sửa danh mục thành công!']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = $this->category->findOrFail($id);

        $category->delete();
        return redirect()->route('categories.index')->with(['message' => 'Xóa danh mục thành công!']);
    }
}

resources/views/admin/categories/create.blade.php
@extends('admin.layouts.app')

@section('title', 'Tạo Category')

@section('content')
    <div class="col-12">
        <div class="card my-4">
            <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
                    <h6 class="text-white text-capitalize ps-3">Tạo Danh Mục</h6>
                </div>
            </div>
            <div class="card-body">
                <form action="{{ route('categories.store') }}" method="post">
                    @csrf
                    <div class="input-group input-group-static mb-4">
                        <label>Tên Danh Mục</label>
                        <input type="text" value="{{ old('name') }}" name="name" class="form-control" placeholder="Nhập tên danh mục">

                        @error('name')
                        <span class="text-danger"> {{ $message }}</span>
                        @enderror
                    </div>

                    <div class="input-group input-group-static mb-4">
                        <label name="group" class="ms-0">Danh Mục Cha</label>
                        <select name="parent_id" class="form-control">
                            <option value="">Chọn Danh Mục Cha</option>
                            @foreach ($parentCategories as $item)
                            <option value="{{ $item->id }}" {{ old('parent_id') == $item->id ? 'selected' : '' }} >{{ $item->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <button type="submit" class="btn btn-submit btn-primary">Tạo</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin.layouts.app')

@section('title', 'Sửa Danh Mục')

@section('content')
    <div class="col-12">
        <div class="card my-4">
            <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
                    <h6 class="text-white text-capitalize ps-3">Sửa Danh Mục</h6>
                </div>
            </div>
            <div class="card-body">
                <form action="{{ route('categories.update', $category->id) }}" method="post">
                    @csrf
                    @method('PUT')
                    <div class="input-group input-group-static mb-4">
                        <label>Tên Danh Mục</label>
                        <input type="text" value="{{ old('name') ?? $category->name }}" name="name" class="form-control" placeholder="Nhập tên danh mục">

                        @error('name')
                        <span class="text-danger"> {{ $message }}</span>
                        @enderror
                    </div>
                    @if ($category->childrens->count() < 1)
                    <div class="input-group input-group-static mb-4">
                        <label name="group" class="ms-0">Danh Mục Cha</label>
                        <select name="parent_id" class="form-control">
                            <option value="">Chọn Danh Mục Cha</option>
                            @foreach ($parentCategories as $item)
                            <option value="{{ $item->id }}" {{ (old('parent_id') ?? $category->parent_id) == $item->id ? 'selected' : '' }} >{{ $item->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    @endif
                    <button type="submit" class="btn btn-submit btn-primary">Sửa</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.app')

@section('title', 'Category')

@section('content')
    <div class="col-12">
        <div class="card my-4">
            <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
                    <h6 class="text-white text-capitalize ps-3">Danh Sách Category</h6>
                </div>
            </div>
            <div class="card-body">
                @if(session('message'))
                    <div class="text-success text-4xl">{{session('message')}}</div>
                @endif
                    <a href="{{ route('categories.create') }}" class="btn btn-primary">Tạo</a>
                <div class="table-responsive p-0">
                    <table class="table table-hover align-items-center mb-0">
                        <thead>
                        <tr>
                            <th class="text-uppercase text-secondary text-md font-weight-bolder opacity-7">ID</th>
                            <th class="text-uppercase text-secondary text-md font-weight-bolder opacity-7 ps-2">Tên
                            </th>
                            <th class="text-uppercase text-secondary text-md font-weight-bolder opacity-7 ps-2">
                                Tên Cha
                            </th>
                            <th class="text-secondary opacity-7 ps-2"></th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach ($categories as $item)
                        <tr>
                            <td>
                                <div class="d-flex px-2 py-1">
                                    <div class="d-flex flex-column justify-content-center">
                                        <h6 class="mb-0 text-md align-middle" style="padding-left: 0.6rem">{{$item->id}}</h6>
                                    </div>
                                </div>
                            </td>
                            <td>
                                <p class="text-md font-weight-bold mb-0">{{$item->name}}</p>
                            </td>
                            <td>
                                <p class="text-md font-weight-bold mb-0">{{$item->parent_name}}</p>
                            </td>
                            <td class="align-middle">
                                <a href="{{route('categories.edit', $item->id)}}" class="btn btn-outline-success font-weight-bold text-xs">
                                    Sửa
                                </a>
                                <form action="{{ route('categories.destroy', $item->id) }}"
                                    id="form-delete{{ $item->id }}" method="post">
                                    @csrf
                                    @method('delete')

                                </form>
                                <button class="btn btn-delete btn-danger" data-id={{ $item->id }}>Delete</button>
                            </td>
                        </tr>
                        @endforeach
                        </tbody>
                    </table>
                    {{$categories->links()}}
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
<script></script>
@endsection